### ISSUE TITLE
MemoryException on NumericalSensors

### ISSUE THREAD

**Issue by bramkragten** [robmarkcole/HASS-data-detective#57] opened 2018-12-17 14:47 UTC
Running on a rpi3

```python
db.fetch_all_data()
numerical_sensors = NumericalSensors(db.master_df)
```
Raises a MemoryException

**Comment by robmarkcole** [comment] 2018-12-17 19:14
Duplicate of https://github.com/robmarkcole/HASS-data-detective/issues/55

**Closed by robmarkcole** 2018-12-17 19:14 UTC
